//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegionLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Steam\\SteamApps\\common\\Arma 3")]
        public string PathToArma {
            get {
                return ((string)(this["PathToArma"]));
            }
            set {
                this["PathToArma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadEmptyWorld {
            get {
                return ((bool)(this["LoadEmptyWorld"]));
            }
            set {
                this["LoadEmptyWorld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SkipIntro {
            get {
                return ((bool)(this["SkipIntro"]));
            }
            set {
                this["SkipIntro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowScriptErrors {
            get {
                return ((bool)(this["ShowScriptErrors"]));
            }
            set {
                this["ShowScriptErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalStartParameters {
            get {
                return ((string)(this["AdditionalStartParameters"]));
            }
            set {
                this["AdditionalStartParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Steam\\SteamApps\\common\\Arma 3\\Legion Addons")]
        public string AddonsPath {
            get {
                return ((string)(this["AddonsPath"]));
            }
            set {
                this["AddonsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00.00.0000")]
        public string LastDownload {
            get {
                return ((string)(this["LastDownload"]));
            }
            set {
                this["LastDownload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pauseOnDesktop {
            get {
                return ((bool)(this["pauseOnDesktop"]));
            }
            set {
                this["pauseOnDesktop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection activeAddons {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["activeAddons"]));
            }
            set {
                this["activeAddons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ServerPasswords {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerPasswords"]));
            }
            set {
                this["ServerPasswords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Profiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Profiles"]));
            }
            set {
                this["Profiles"] = value;
            }
        }
    }
}
